// ui/src/components/DataExtractorApp.jsx
import { useState } from 'react'

function DataExtractorApp({ user, authService }) {
  const getLocationDisplay = () => {
    if (user.activeLocation) {
      return `Location: ${user.activeLocation}`
    }
    return `Company: ${user.companyId}`
  }

  return (
    <div className="app-container">
      <header className="app-header">
        <h1>Data Extractor</h1>
        <div className="user-info">
          <span className="user-name">{user.userName}</span>
          <span className="location-badge">{getLocationDisplay()}</span>
        </div>
      </header>
      
      <main className="app-content">
        <div className="welcome-section">
          <h2>Welcome to Your Conversation Data Extractor</h2>
          <p>Extract valuable insights from your GoHighLevel conversations automatically.</p>
          
          <div className="stats-grid">
            <div className="stat-card">
              <h3>Location ID</h3>
              <p className="stat-value">{user.locationId}</p>
            </div>
            
            <div className="stat-card">
              <h3>User Role</h3>
              <p className="stat-value">{user.role}</p>
            </div>
            
            <div className="stat-card">
              <h3>Context Type</h3>
              <p className="stat-value">{user.type}</p>
            </div>
          </div>
        </div>
        
        <div className="features-section">
          <h3>Available Features</h3>
          <div className="feature-grid">
            <div className="feature-card">
              <div className="feature-icon">🔍</div>
              <h4>Data Extraction</h4>
              <p>Set up custom fields to extract from conversations</p>
              <button className="feature-button">Configure</button>
            </div>
            
            <div className="feature-card">
              <div className="feature-icon">⚙️</div>
              <h4>Rules & Triggers</h4>
              <p>Define when and how data should be extracted</p>
              <button className="feature-button">Manage</button>
            </div>
            
            <div className="feature-card">
              <div className="feature-icon">📊</div>
              <h4>Analytics</h4>
              <p>View extraction performance and insights</p>
              <button className="feature-button">View Reports</button>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

export default DataExtractorApp

// src/ui/src/components/DataExtractorApp.vue
<template>
  <div class="app-container">
    <div v-if="loading" class="loading-container">
      <div class="loading-spinner"></div>
      <p>Loading your data extractor...</p>
    </div>
    
    <div v-else-if="error" class="error-container">
      <h2>Access Error</h2>
      <p>{{ error }}</p>
      <button @click="retryAuth" class="retry-button">Retry</button>
    </div>
    
    <div v-else-if="user" class="main-app">
      <header class="app-header">
        <h1>Data Extractor</h1>
        <div class="user-info">
          <span class="user-name">{{ user.userName }}</span>
          <span class="location-badge">{{ getLocationDisplay() }}</span>
        </div>
      </header>
      
      <main class="app-content">
        <div class="welcome-section">
          <h2>Welcome to Your Conversation Data Extractor</h2>
          <p>Extract valuable insights from your GoHighLevel conversations automatically.</p>
          
          <div class="stats-grid">
            <div class="stat-card">
              <h3>Location ID</h3>
              <p class="stat-value">{{ user.locationId }}</p>
            </div>
            
            <div class="stat-card">
              <h3>User Role</h3>
              <p class="stat-value">{{ user.role }}</p>
            </div>
            
            <div class="stat-card">
              <h3>Context Type</h3>
              <p class="stat-value">{{ user.type }}</p>
            </div>
          </div>
        </div>
        
        <div class="features-section">
          <h3>Available Features</h3>
          <div class="feature-grid">
            <div class="feature-card">
              <div class="feature-icon">🔍</div>
              <h4>Data Extraction</h4>
              <p>Set up custom fields to extract from conversations</p>
              <button class="feature-button">Configure</button>
            </div>
            
            <div class="feature-card">
              <div class="feature-icon">⚙️</div>
              <h4>Rules & Triggers</h4>
              <p>Define when and how data should be extracted</p>
              <button class="feature-button">Manage</button>
            </div>
            
            <div class="feature-card">
              <div class="feature-icon">📊</div>
              <h4>Analytics</h4>
              <p>View extraction performance and insights</p>
              <button class="feature-button">View Reports</button>
            </div>
          </div>
        </div>
      </main>
    </div>
  </div>
</template>

<script>
import { AuthService } from '../services/authService.js';

export default {
  name: 'DataExtractorApp',
  data() {
    return {
      user: null,
      loading: true,
      error: null,
      authService: new AuthService()
    }
  },
  async mounted() {
    await this.initializeApp();
  },
  methods: {
    async initializeApp() {
      try {
        this.loading = true;
        this.error = null;
        
        // Get user data from GHL SSO
        this.user = await this.authService.getUserData();
        
        console.log('User authenticated:', this.user);
      } catch (error) {
        console.error('Authentication error:', error);
        this.error = 'Failed to authenticate user. Please ensure you are accessing this from within GoHighLevel.';
      } finally {
        this.loading = false;
      }
    },
    
    async retryAuth() {
      await this.initializeApp();
    },
    
    getLocationDisplay() {
      if (this.user.activeLocation) {
        return `Location: ${this.user.activeLocation}`;
      }
      return `Company: ${this.user.companyId}`;
    }
  }
}
</script>

<style scoped>
.app-container {
  min-height: 100vh;
  background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
}

.loading-container, .error-container {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
  text-align: center;
  padding: 2rem;
}

.loading-spinner {
  width: 40px;
  height: 40px;
  border: 4px solid #f3f3f3;
  border-top: 4px solid #3498db;
  border-radius: 50%;
  animation: spin 1s linear infinite;
  margin-bottom: 1rem;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

.error-container h2 {
  color: #e74c3c;
  margin-bottom: 1rem;
}

.retry-button {
  background: #3498db;
  color: white;
  border: none;
  padding: 0.75rem 1.5rem;
  border-radius: 6px;
  cursor: pointer;
  font-weight: 500;
  margin-top: 1rem;
}

.retry-button:hover {
  background: #2980b9;
}

.main-app {
  min-height: 100vh;
}

.app-header {
  background: white;
  padding: 1rem 2rem;
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.app-header h1 {
  margin: 0;
  color: #2c3e50;
  font-size: 1.8rem;
}

.user-info {
  display: flex;
  align-items: center;
  gap: 1rem;
}

.user-name {
  font-weight: 600;
  color: #34495e;
}

.location-badge {
  background: #3498db;
  color: white;
  padding: 0.25rem 0.75rem;
  border-radius: 20px;
  font-size: 0.85rem;
  font-weight: 500;
}

.app-content {
  padding: 2rem;
  max-width: 1200px;
  margin: 0 auto;
}

.welcome-section {
  background: white;
  padding: 2rem;
  border-radius: 12px;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
  margin-bottom: 2rem;
  text-align: center;
}

.welcome-section h2 {
  margin: 0 0 1rem 0;
  color: #2c3e50;
  font-size: 2rem;
}

.welcome-section p {
  color: #7f8c8d;
  font-size: 1.1rem;
  margin-bottom: 2rem;
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 1rem;
  margin-top: 2rem;
}

.stat-card {
  background: #f8f9fa;
  padding: 1.5rem;
  border-radius: 8px;
  border: 1px solid #e9ecef;
}

.stat-card h3 {
  margin: 0 0 0.5rem 0;
  color: #6c757d;
  font-size: 0.9rem;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.stat-value {
  margin: 0;
  color: #2c3e50;
  font-size: 1.2rem;
  font-weight: 600;
  word-break: break-all;
}

.features-section {
  background: white;
  padding: 2rem;
  border-radius: 12px;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
}

.features-section h3 {
  margin: 0 0 1.5rem 0;
  color: #2c3e50;
  font-size: 1.5rem;
}

.feature-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 1.5rem;
}

.feature-card {
  background: #f8f9fa;
  padding: 1.5rem;
  border-radius: 8px;
  border: 1px solid #e9ecef;
  text-align: center;
  transition: transform 0.2s ease;
}

.feature-card:hover {
  transform: translateY(-2px);
}

.feature-icon {
  font-size: 2rem;
  margin-bottom: 1rem;
}

.feature-card h4 {
  margin: 0 0 0.5rem 0;
  color: #2c3e50;
  font-size: 1.2rem;
}

.feature-card p {
  margin: 0 0 1rem 0;
  color: #6c757d;
  font-size: 0.9rem;
}

.feature-button {
  background: #3498db;
  color: white;
  border: none;
  padding: 0.5rem 1rem;
  border-radius: 6px;
  cursor: pointer;
  font-weight: 500;
  transition: background-color 0.2s ease;
}

.feature-button:hover {
  background: #2980b9;
}
</style>
