// src/ui/src/components/DataExtractorApp.vue
<template>
  <div class="app-container">
    <div v-if="loading" class="loading-container">
      <div class="loading-spinner"></div>
      <p>Loading your data extractor...</p>
    </div>
    
    <div v-else-if="error" class="error-container">
      <h2>Access Error</h2>
      <p>{{ error }}</p>
      <button @click="retryAuth" class="retry-button">Retry</button>
    </div>
    
    <div v-else-if="user" class="main-app">
      <header class="app-header">
        <h1>Data Extractor</h1>
        <div class="user-info">
          <span class="user-name">{{ user.userName }}</span>
          <span class="location-badge">{{ getLocationDisplay() }}</span>
        </div>
      </header>
      
      <main class="app-content">
        <div class="welcome-section">
          <h2>Welcome to Your Conversation Data Extractor</h2>
          <p>Extract valuable insights from your GoHighLevel conversations automatically.</p>
          
          <div class="stats-grid">
            <div class="stat-card">
              <h3>Location ID</h3>
              <p class="stat-value">{{ user.locationId }}</p>
            </div>
            
            <div class="stat-card">
              <h3>User Role</h3>
              <p class="stat-value">{{ user.role }}</p>
            </div>
            
            <div class="stat-card">
              <h3>Context Type</h3>
              <p class="stat-value">{{ user.type }}</p>
            </div>
          </div>
        </div>
        
        <div class="features-section">
          <h3>Available Features</h3>
          <div class="feature-grid">
            <div class="feature-card">
              <div class="feature-icon">🔍</div>
              <h4>Data Extraction</h4>
              <p>Set up custom fields to extract from conversations</p>
              <button class="feature-button">Configure</button>
            </div>
            
            <div class="feature-card">
              <div class="feature-icon">⚙️</div>
              <h4>Rules & Triggers</h4>
              <p>Define when and how data should be extracted</p>
              <button class="feature-button">Manage</button>
            </div>
            
            <div class="feature-card">
              <div class="feature-icon">📊</div>
              <h4>Analytics</h4>
              <p>View extraction performance and insights</p>
              <button class="feature-button">View Reports</button>
            </div>
          </div>
        </div>
      </main>
    </div>
  </div>
</template>

<script>
import { AuthService } from '../services/authService.js';

export default {
  name: 'DataExtractorApp',
  data() {
    return {
      user: null,
      loading: true,
      error: null,
      authService: new AuthService()
    }
  },
  async mounted() {
    await this.initializeApp();
  },
  methods: {
    async initializeApp() {
      try {
        this.loading = true;
        this.error = null;
        
        // Get user data from GHL SSO
        this.user = await this.authService.getUserData();
        
        console.log('User authenticated:', this.user);
      } catch (error) {
        console.error('Authentication error:', error);
        this.error = 'Failed to authenticate user. Please ensure you are accessing this from within GoHighLevel.';
      } finally {
        this.loading = false;
      }
    },
    
    async retryAuth() {
      await this.initializeApp();
    },
    
    getLocationDisplay() {
      if (this.user.activeLocation) {
        return `Location: ${this.user.activeLocation}`;
      }
      return `Company: ${this.user.companyId}`;
    }
  }
}
</script>

<style scoped>
.app-container {
  min-height: 100vh;
  background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
}

.loading-container, .error-container {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
  text-align: center;
  padding: 2rem;
}

.loading-spinner {
  width: 40px;
  height: 40px;
  border: 4px solid #f3f3f3;
  border-top: 4px solid #3498db;
  border-radius: 50%;
  animation: spin 1s linear infinite;
  margin-bottom: 1rem;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

.error-container h2 {
  color: #e74c3c;
  margin-bottom: 1rem;
}

.retry-button {
  background: #3498db;
  color: white;
  border: none;
  padding: 0.75rem 1.5rem;
  border-radius: 6px;
  cursor: pointer;
  font-weight: 500;
  margin-top: 1rem;
}

.retry-button:hover {
  background: #2980b9;
}

.main-app {
  min-height: 100vh;
}

.app-header {
  background: white;
  padding: 1rem 2rem;
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.app-header h1 {
  margin: 0;
  color: #2c3e50;
  font-size: 1.8rem;
}

.user-info {
  display: flex;
  align-items: center;
  gap: 1rem;
}

.user-name {
  font-weight: 600;
  color: #34495e;
}

.location-badge {
  background: #3498db;
  color: white;
  padding: 0.25rem 0.75rem;
  border-radius: 20px;
  font-size: 0.85rem;
  font-weight: 500;
}

.app-content {
  padding: 2rem;
  max-width: 1200px;
  margin: 0 auto;
}

.welcome-section {
  background: white;
  padding: 2rem;
  border-radius: 12px;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
  margin-bottom: 2rem;
  text-align: center;
}

.welcome-section h2 {
  margin: 0 0 1rem 0;
  color: #2c3e50;
  font-size: 2rem;
}

.welcome-section p {
  color: #7f8c8d;
  font-size: 1.1rem;
  margin-bottom: 2rem;
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 1rem;
  margin-top: 2rem;
}

.stat-card {
  background: #f8f9fa;
  padding: 1.5rem;
  border-radius: 8px;
  border: 1px solid #e9ecef;
}

.stat-card h3 {
  margin: 0 0 0.5rem 0;
  color: #6c757d;
  font-size: 0.9rem;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.stat-value {
  margin: 0;
  color: #2c3e50;
  font-size: 1.2rem;
  font-weight: 600;
  word-break: break-all;
}

.features-section {
  background: white;
  padding: 2rem;
  border-radius: 12px;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
}

.features-section h3 {
  margin: 0 0 1.5rem 0;
  color: #2c3e50;
  font-size: 1.5rem;
}

.feature-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 1.5rem;
}

.feature-card {
  background: #f8f9fa;
  padding: 1.5rem;
  border-radius: 8px;
  border: 1px solid #e9ecef;
  text-align: center;
  transition: transform 0.2s ease;
}

.feature-card:hover {
  transform: translateY(-2px);
}

.feature-icon {
  font-size: 2rem;
  margin-bottom: 1rem;
}

.feature-card h4 {
  margin: 0 0 0.5rem 0;
  color: #2c3e50;
  font-size: 1.2rem;
}

.feature-card p {
  margin: 0 0 1rem 0;
  color: #6c757d;
  font-size: 0.9rem;
}

.feature-button {
  background: #3498db;
  color: white;
  border: none;
  padding: 0.5rem 1rem;
  border-radius: 6px;
  cursor: pointer;
  font-weight: 500;
  transition: background-color 0.2s ease;
}

.feature-button:hover {
  background: #2980b9;
}
</style>

// src/components/DataExtractorApp.jsx
import React from 'react'
import { Routes, Route } from 'react-router-dom'
import UserLinking from './UserLinking'
import DataExtractionModule from './DataExtractionModule'
import InstallationGuide from './InstallationGuide'
import Navigation from './Navigation'

function DataExtractorApp({ user, authService }) {
  const getLocationDisplay = () => {
    if (user.activeLocation) {
      return `Location: ${user.activeLocation}`
    }
    return `Company: ${user.companyId}`
  }

  const getUserModeDisplay = () => {
    if (user.standaloneMode) return 'STANDALONE'
    return null
  }

  const handleLinkingComplete = () => {
    // Refresh the page or update state to reflect the linked configuration
    window.location.reload()
  }

  const handleInstallationComplete = () => {
    // Refresh the page to reload with new tokens
    window.location.reload()
  }

  // Check if user needs OAuth installation (has missing tokens)
  const needsOAuthInstallation = () => {
    if (user.standaloneMode) return false // Already installed via OAuth
    
    // Check token validation from user context
    if (user.tokenValidation) {
      return !user.tokenValidation.isValid && 
             ['missing_access_token', 'missing_refresh_token'].includes(user.tokenValidation.status)
    }
    
    // Fallback check based on token status
    return user.tokenStatus === 'missing'
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white shadow-sm border-b">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center py-4">
            <h1 className="text-2xl font-bold text-gray-900">Data Extractor</h1>
            <div className="flex items-center space-x-4">
              <span className="text-sm font-medium text-gray-700">{user.userName}</span>
              <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                {getLocationDisplay()}
              </span>
              {getUserModeDisplay() && (
                <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800">
                  {getUserModeDisplay()}
                </span>
              )}
            </div>
          </div>
        </div>
      </header>
      
      <main className="max-w-7xl mx-auto py-8 px-4 sm:px-6 lg:px-8">
        {/* Show installation guide if OAuth setup is needed */}
        {needsOAuthInstallation() && (
          <div className="mb-8">
            <InstallationGuide user={user} onInstallationComplete={handleInstallationComplete} />
          </div>
        )}
        
        {/* User Linking Component - shows if there are unlinked configurations */}
        {!user.standaloneMode && !needsOAuthInstallation() && (
          <UserLinking user={user} authService={authService} onLinkingComplete={handleLinkingComplete} />
        )}
        
        {!needsOAuthInstallation() && <Navigation />}
        
        <Routes>
          <Route path="/" element={<DashboardHome user={user} needsOAuth={needsOAuthInstallation()} />} />
          <Route path="/data-extraction" element={
            needsOAuthInstallation() ? (
              <div className="text-center py-8">
                <p className="text-gray-600">Please complete the OAuth installation first.</p>
              </div>
            ) : (
              <DataExtractionModule user={user} authService={authService} />
            )
          } />
        </Routes>
      </main>
    </div>
  )
}

function DashboardHome({ user, needsOAuth }) {
  if (needsOAuth) {
    return (
      <div className="space-y-8">
        <div className="mb-8">
          <h2 className="text-3xl font-bold text-gray-900 mb-2">
            Setup Required
          </h2>
          <p className="text-lg text-gray-600">
            Complete the OAuth installation above to start extracting data from your GoHighLevel conversations.
          </p>
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-8">
      <div className="mb-8">
        <h2 className="text-3xl font-bold text-gray-900 mb-2">
          Welcome to Your Conversation Data Extractor
        </h2>
        <p className="text-lg text-gray-600">
          Extract valuable insights from your GoHighLevel conversations automatically.
        </p>
        {user.standaloneMode && (
          <div className="mt-4 bg-green-50 border border-green-200 rounded-lg p-4">
            <p className="text-sm text-green-800">
              <strong>Standalone Mode:</strong> You're using this app as a standalone installation. 
              This installation was completed via OAuth and has proper access tokens.
            </p>
            <p className="text-xs text-green-700 mt-1">
              Installed: {new Date(user.installedAt).toLocaleString()}
            </p>
          </div>
        )}
      </div>
      
      <div className="bg-white rounded-lg shadow">
        <div className="px-6 py-4 border-b border-gray-200">
          <h3 className="text-lg font-medium text-gray-900">Available Features</h3>
        </div>
        <div className="p-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="text-center p-6 border border-gray-200 rounded-lg hover:shadow-md transition-shadow">
              <div className="text-4xl mb-4">🔍</div>
              <h4 className="text-lg font-semibold text-gray-900 mb-2">Data Extraction</h4>
              <p className="text-gray-600 mb-4">Set up custom fields to extract from conversations</p>
              <a
                href="/data-extraction"
                className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-md transition-colors inline-block"
              >
                Configure
              </a>
            </div>
            
            <div className="text-center p-6 border border-gray-200 rounded-lg hover:shadow-md transition-shadow">
              <div className="text-4xl mb-4">⚙️</div>
              <h4 className="text-lg font-semibold text-gray-900 mb-2">Rules & Triggers</h4>
              <p className="text-gray-600 mb-4">Define when and how data should be extracted</p>
              <button className="bg-gray-400 text-white px-4 py-2 rounded-md cursor-not-allowed">
                Coming Soon
              </button>
            </div>
            
            <div className="text-center p-6 border border-gray-200 rounded-lg hover:shadow-md transition-shadow">
              <div className="text-4xl mb-4">📊</div>
              <h4 className="text-lg font-semibold text-gray-900 mb-2">Analytics</h4>
              <p className="text-gray-600 mb-4">View extraction performance and insights</p>
              <button className="bg-gray-400 text-white px-4 py-2 rounded-md cursor-not-allowed">
                Coming Soon
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default DataExtractorApp
